language: groovy
sudo: true
branches:
  only:
  - master
install:
- sudo -H pip install mkdocs
- sudo -H pip install mkdocs-material
script:
- if [[ "${TRAVIS_PULL_REQUEST}" != "false" ]]; then chmod +x pull-request.sh && ./pull-request.sh; else chmod +x gh-pages-deploy.sh && ./gh-pages-deploy.sh; fi;
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.m2"