language: groovy
sudo: true
branches:
  only:
  - master
install:
- sudo pip install mkdocs
- sudo pip install mkdocs-material
script:
- chmod +x gh-pages-deploy.sh
- ./gh-pages-deploy.sh
cache:
  directories:
  - "$HOME/.cache/pip"