language: groovy
branches:
  only:
  - master
install:
- sudo pip install mkdocs
- sudo pip install mkdocs-material
script:
- cd documentation && ./gh-pages-deploy.sh
cache:
  directories:
  - "$HOME/.cache/pip"